# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Dress CRPS
#'
#' @param m vector of kernel means
#' @param s vector of kernel standard deviations
#' @param y observation 
#' @return crps
#' @export
dresscrps_cpp <- function(m, s, y) {
    .Call('SpecsVerification_dresscrps_cpp', PACKAGE = 'SpecsVerification', m, s, y)
}

